apiVersion: v1
kind: ConfigMap
metadata:
    name: deceuvel-api-configs
data:
    mongo-init-db: "deceuvel"
---
#
apiVersion: v1
kind: ConfigMap
metadata:
    name: mongo-init-script
data:
    mongo-init.sh: |
        #!/bin/bash

        echo '################ MONGO ENTRYPOINT START ################';

        set -e

        mongo <<EOF
        use $MONGO_INITDB_DATABASE

        db.createUser({
          user: '$MONGO_INITDB_ROOT_USERNAME',
          pwd: '$MONGO_INITDB_ROOT_PASSWORD',
          roles: [{
            role: 'readWrite',
            db: '$MONGO_INITDB_DATABASE'
          }]
        })
        EOF

        echo '################ MONGO ENTRYPOINT END ################';
