apiVersion: v1
kind: Service
metadata:
  name: deceuvel-api-svc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: deceuvel-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deceuvel-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deceuvel-api
  template:
    metadata:
      labels:
        app: deceuvel-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
      - name: regcred
      containers:
      - name: deceuvel-api-container
        image: test.compendium.sovereignnature.ch/deceuvel-api:%CONTAINER_TAG%
        #imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: APP_PORT
          value: "80"
        - name: MONGO_DATABASE_PORT
          value: "27017"
        - name: MONGO_DATABASE_HOST
          value: mongo-svc
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
                name: deceuvel-api-secrets
                key: mongo-root
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
                name: deceuvel-api-secrets
                key: mongo-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
                name: deceuvel-api-configs
                key: mongo-init-db
