name: Build Docker Image
on:
    push:
        #branches:
        #    - 'main'
        tags:
            - v*
    #pull_request:
    #    branches:
    #      - 'main'
    workflow_dispatch:
        inputs:
            tag:
                description: 'Image tag to deploy'
                required: true
                #default: 'v1.0.0'
jobs:
    Build-Image:
        runs-on: ubuntu-latest
        #if: startsWith(github.event.head_commit.message, 'release')
        #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        steps:
            - name: Set ENV Variables
              run: |
                export REP_NAME=$(echo ${{github.repository}} | awk '{split($0,a,"/"); print a[2]}')
                echo "REP_NAME=$REP_NAME" >> $GITHUB_ENV
                if [[ ${{ github.event_name }} = "workflow_dispatch" ]]; then export CONTAINER_TAG=${{ github.event.inputs.tag }}; else export CONTAINER_TAG=$(echo ${{github.ref}} | sed 's/refs\/tags\///'); fi
                echo "CONTAINER_TAG=$CONTAINER_TAG" >> $GITHUB_ENV
                export REGISTRY=test.compendium.sovereignnature.ch
                echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV
                export FULL_TAG="$REGISTRY/$REP_NAME:$CONTAINER_TAG"
                echo "FULL_TAG=$FULL_TAG" >> $GITHUB_ENV
                echo "Full Tag "$FULL_TAG

            - name: Check-out Repository Code
              uses: actions/checkout@v2

            - name: Build Docker Image
              run: docker build ${{ github.workspace }} -t ${{ env.FULL_TAG }} --build-arg IMG_TAG_VAR=${{ env.CONTAINER_TAG }}

            - name: Deploy Locally
              run: |
                touch .env
                echo "MONGO_INITDB_ROOT_USERNAME=dummy-admin" >> .env
                echo "MONGO_INITDB_ROOT_PASSWORD=dummy-password" >> .env
                echo "MONGO_INITDB_DATABASE=deceuvel" >> .env
                echo "MONGO_DATABASE_PORT=27017" >> .env
                echo "APP_PORT=8080" >> .env
                echo "IMG_TAG=${{ env.FULL_TAG }}" >> .env
                cat .env
                docker-compose --build up -d
                sleep 5

            - name: Heartbeat Test
              run: |
                export RES=$(curl -s -o /dev/null -I -w "%{http_code}" http://localhost:8080/)
                echo $RES
                [[ $RES = "200" ]]

            - name: Login to Registry
              uses: docker/login-action@v1
              with:
                registry: ${{ env.REGISTRY }}
                username: sni-admin
                password: ${{secrets.REGISTRY_PASSWORD}}

            - name: Upload Image to Registry
              run: docker image push ${{ env.FULL_TAG }}
