name: Build Docker Image
on:
    push:
        branches:
            - 'main'
        tags:
            - v*
jobs:
    Deploy-Image:
        runs-on: ubuntu-latest
        #if: startsWith(github.event.head_commit.message, 'release')
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        steps:
            #- run: echo "Triggered by a ${{ github.event_name }} event."
            #- run: echo "Commit Message ${{ github.event.head_commit }}"
            #- run: echo "Running on a ${{ runner.os }} server."
            #- run: echo "Branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
            - name: Set CONTAINER_TAG
              run: echo "CONTAINER_TAG=$(sed 's#${{github.ref}}#refs/tags/#')" >> $GITHUB_ENV
            - name: Test
              run: echo "Container Tag $CONTAINER_TAG"
            - name: Check out repository code
              uses: actions/checkout@v2
            #- run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            - name: Build Docker Image
              run: docker build ${{ github.workspace }} -t deceuvel-api:$CONTAINER_TAG
            #- name: List Docker Images
            #  run: docker images
            - name: Export Docker Image
              run: docker save deceuvel-api > deceuvel-api.tar
            - name: Upload Image to Cluster
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.HOST_KEY }}
                port: ${{ secrets.SSH_PORT }}
                source: "deceuvel-api.tar"
                target: "~/"
            - name: Import image in the cluster
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.HOST_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: "(echo \"${{ secrets.SUDO }}\" | sudo -S microk8s ctr image import deceuvel-api.tar) && (echo \"${{ secrets.SUDO }}\" | sudo -S microk8s ctr images ls) && rm deceuvel-api.tar"
            - run: rm deceuvel-api.tar
            - run: sed -i 's/%CONTAINER_TAG%/$CONTAINER_TAG/g' deployment/deploy-api.yml
            - name: Deploy
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                args: apply -f deployment/deploy-api.yml -n deceuvel-api-dev
            # Force restart
            - name: Rollout
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                args: rollout restart deployment deceuvel-api-deployment -n deceuvel-api-dev
            #- run: echo "This job's status is ${{ job.status }}."
